import {
  Footprints,
  Bird,
  Satellite,
  Building2,
  Images,
  Play,
  Home,
  Map,
  Camera,
  Compass,
  Layers,
  TreePine,
  Car,
  Sun,
  Star,
  Eye,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "./types";

export const ICONS: Record<IconName, LucideIcon> = {
  walk: Footprints,
  bird: Bird,
  satellite: Satellite,
  units: Building2,
  gallery: Images,
  play: Play,
  home: Home,
  map: Map,
  camera: Camera,
  compass: Compass,
  layers: Layers,
  tree: TreePine,
  car: Car,
  sun: Sun,
  star: Star,
  eye: Eye,
};

export const ICON_OPTIONS: { value: IconName; label: string }[] = [
  { value: "walk", label: "Walk" },
  { value: "bird", label: "Bird" },
  { value: "satellite", label: "Satellite" },
  { value: "units", label: "Units" },
  { value: "gallery", label: "Gallery" },
  { value: "play", label: "Play" },
  { value: "home", label: "Home" },
  { value: "map", label: "Map" },
  { value: "camera", label: "Camera" },
  { value: "compass", label: "Compass" },
  { value: "layers", label: "Layers" },
  { value: "tree", label: "Park" },
  { value: "car", label: "Drive" },
  { value: "sun", label: "Sun" },
  { value: "star", label: "Star" },
  { value: "eye", label: "View" },
];
